### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by igniscyan** [Otttter/Group-Leaver#1]
Getting a trojan warning.... Safe to ignore this?

**Comment by Otttter** [comment]
That's extremely strange. If it makes you feel better you can copy and paste the code itself instead of downloading it from gh. The line that does all the magic is at line 22. It's a very simple script. If you could shoot me a screenshot of the file and the anti-virus message to my email ottter@riseup.net I'd appreciate it (Because I'm genuinely curious now) but unless you downloaded it from somewhere else or some other dodgy way, you should be fine.

**Comment by igniscyan** [comment]
Hey, I ended up doing just that. Script was indeed simple, don't know why it's spitting the trojan warning at me. I'm sending over a screenshot now! Thanks for the fast response :)

**Comment by Otttter** [comment]
No problem! Glad it worked out for you!
