### ISSUE TITLE
can my acc get ban if i use this

### ISSUE THREAD

**Issue by Lolicchi** [Otttter/Group-Leaver#3]
someone asked me to accept their friend request and as soon as i did i got added into 9k+ group chats, so if i use this will my acc get banned bcoz this comes under self-botting. Im currently using a autoclicker to leave the groups, thx.

**Comment by Otttter** [comment]
It's kinda a grey area. You're not causing any harm to anyone; however you are blowing up discord's api with requests... so its a no with a hint of yes. I've been using this script, plus all my dev shit and selfbot tests etc. on my main since I registered for discord and I've never had any issues. 🤷

**Comment by Otttter** [comment]
![selfbows](https://user-images.githubusercontent.com/45733769/142712808-32325d61-ef42-4be8-89f0-76f6d05f7165.png)
